# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af1f7733f57c0a839768b859babec023b273538ce45c66c49233717c725a86fa62af940cfe01d01ac104a436213ea70fa866a88353c849541add9b7aacb100d6

test:
  secret_key_base: 5657bdf29530a670e3706f3c4f59f6ef8c9a7d4cad3327c1482504b5faf11e15956f5520e375ea3c4dc55c34ea68b474b29b43ce16e223cdf8c7222ea31b663d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
